services:
  app:
    build: .
    expose:
      - "8000"
    volumes:
      - .:/app
      - db_data:/app/db
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///db/shortener.db

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db_data: